// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_6izncHk8h9gmJo2hrfel50KgbrrN88',
    appId: '1:639651754189:web:fc409d8bc1e3f25ef73984',
    messagingSenderId: '639651754189',
    projectId: 'crgtransp72app',
    authDomain: 'crgtransp72app.firebaseapp.com',
    storageBucket: 'crgtransp72app.firebasestorage.app',
    measurementId: 'G-BMNZFYZER2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6CsiOLHj9EoNPQ1eOjGoPlQnZtUTwa-A',
    appId: '1:639651754189:android:5d7185fa20f6905af73984',
    messagingSenderId: '639651754189',
    projectId: 'crgtransp72app',
    storageBucket: 'crgtransp72app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADofudyIz4JIPWOwWVxlBMIbuJQkOOrvs',
    appId: '1:639651754189:ios:7a02ef851b41fecdf73984',
    messagingSenderId: '639651754189',
    projectId: 'crgtransp72app',
    storageBucket: 'crgtransp72app.firebasestorage.app',
    iosBundleId: 'ru.app72.crgtransp72app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADofudyIz4JIPWOwWVxlBMIbuJQkOOrvs',
    appId: '1:639651754189:ios:52146d603ffce226f73984',
    messagingSenderId: '639651754189',
    projectId: 'crgtransp72app',
    storageBucket: 'crgtransp72app.firebasestorage.app',
    iosBundleId: 'com.example.crgtransp72app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_6izncHk8h9gmJo2hrfel50KgbrrN88',
    appId: '1:639651754189:web:c01088218ee28517f73984',
    messagingSenderId: '639651754189',
    projectId: 'crgtransp72app',
    authDomain: 'crgtransp72app.firebaseapp.com',
    storageBucket: 'crgtransp72app.firebasestorage.app',
    measurementId: 'G-XTS17CHYC8',
  );
}
